### ISSUE TITLE
“Imagine if..." quote wrongly attributed to Satoshi Nakamoto

### ISSUE THREAD

**Issue by dergigi** [bitcoinexplained/bitcoinexplained.github.io#3]
The following quote is not from Satoshi directly, but from [Phil Champagne](https://twitter.com/egg_descrambler), author of [The Book of Satoshi](https://www.goodreads.com/book/show/22619661-the-book-of-satoshi).

![Screenshot from 2020-05-23 11-29-48](https://user-images.githubusercontent.com/109058/82727525-537a6800-9ceb-11ea-9f0e-8ba1c27a3c66.png)

It is part of the introduction of Chapter 23 of the book:
![Screenshot from 2020-05-23 11-47-53](https://user-images.githubusercontent.com/109058/82727565-89b7e780-9ceb-11ea-94b0-796ea47f8143.png)

**Comment by bitcoinexplained** [comment]
Thanks for pointing out, fixed it!
